import { Controller, Logger } from '@nestjs/common';
import { EventPattern, Payload } from '@nestjs/microservices';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';

import { Conversation, ConversationDocument } from '../chat/schemas/conversation.schema';
import { Message, MessageDocument } from '../chat/schemas/message.schema';

import { CHAT_EVENTS } from './events/chat.events';
import { KafkaProducerService } from './kafka-producer.service';

interface AgentBotReplyEvent {
  conversationId: string;
  botUserId: string;
  content: string;
  metadata?: Record<string, any> | null;
}

/**
 * Persists messages generated by the AI agent and broadcasts them to clients
 * so the bot's reply appears in the conversation in real time.
 */
@Controller()
export class AgentReplyConsumer {
  private readonly logger = new Logger(AgentReplyConsumer.name);

  constructor(
    @InjectModel(Message.name) private messageModel: Model<MessageDocument>,
    @InjectModel(Conversation.name)
    private conversationModel: Model<ConversationDocument>,
    private kafkaProducer: KafkaProducerService
  ) {}

  @EventPattern('agent.bot_reply')
  async handleBotReply(@Payload() event: AgentBotReplyEvent): Promise<void> {
    if (!event?.conversationId || !event?.content?.trim()) return;

    try {
      const convId = new Types.ObjectId(event.conversationId);
      const conv = await this.conversationModel.findById(convId);
      if (!conv) {
        this.logger.warn(`Conversation ${event.conversationId} not found for bot reply`);
        return;
      }

      const msg = await this.messageModel.create({
        conversationId: convId,
        senderId: event.botUserId,
        type: 'text',
        content: event.content,
        metadata: event.metadata ?? { isBot: true },
        attachments: [],
      });

      await this.conversationModel.updateOne(
        { _id: convId },
        {
          lastMessage: {
            messageId: (msg._id as Types.ObjectId).toString(),
            senderId: event.botUserId,
            content: event.content,
            type: 'text',
            sentAt: msg.createdAt,
          },
        }
      );

      const participantIds = conv.participants.map((p: any) => p.userId);

      await this.kafkaProducer.emit(CHAT_EVENTS.MESSAGE_CREATED, {
        messageId: (msg._id as Types.ObjectId).toString(),
        conversationId: event.conversationId,
        senderId: event.botUserId,
        participants: participantIds,
        content: event.content,
        type: 'text',
        metadata: event.metadata ?? { isBot: true },
        attachments: [],
        createdAt: msg.createdAt,
      });

      await this.kafkaProducer.emit(CHAT_EVENTS.CONVERSATION_UPDATED, {
        conversationId: event.conversationId,
        participants: participantIds,
        lastMessage: {
          messageId: (msg._id as Types.ObjectId).toString(),
          senderId: event.botUserId,
          content: event.content,
          type: 'text',
          sentAt: msg.createdAt,
        },
      });

      this.logger.log(`Bot reply persisted for conversation ${event.conversationId}`);
    } catch (err) {
      this.logger.error(`Failed to handle bot reply: ${(err as Error).message}`);
    }
  }

  @EventPattern('agent.typing')
  async handleTyping(
    @Payload() event: { conversationId: string; botUserId: string; typing: boolean }
  ) {
    if (!event?.conversationId) return;
    try {
      const conv = await this.conversationModel
        .findById(event.conversationId)
        .select('participants')
        .lean();
      if (!conv) return;
      const participantIds = conv.participants.map((p: any) => p.userId);
      await this.kafkaProducer.emit('chat.bot.typing', {
        conversationId: event.conversationId,
        botUserId: event.botUserId,
        typing: event.typing,
        participants: participantIds,
      });
    } catch (err) {
      this.logger.warn(`Failed to broadcast typing: ${(err as Error).message}`);
    }
  }
}
