import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type TaskDocument = Task & Document;

export type TaskStatus = 'todo' | 'in_progress' | 'done';
export type TaskPriority = 'low' | 'medium' | 'high';

@Schema({ _id: true, timestamps: { createdAt: true, updatedAt: false } })
export class TaskComment {
  _id: Types.ObjectId;

  @Prop({ required: true })
  userId: string;

  @Prop({ required: true })
  content: string;

  createdAt: Date;
}

export const TaskCommentSchema = SchemaFactory.createForClass(TaskComment);

@Schema({ timestamps: true, collection: 'tasks' })
export class Task {
  _id: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'Conversation', required: true, index: true })
  conversationId: Types.ObjectId;

  @Prop({ required: true })
  title: string;

  @Prop({ default: '' })
  description: string;

  @Prop({ default: null })
  assigneeId: string | null;

  @Prop({ required: true })
  createdBy: string;

  @Prop({ enum: ['todo', 'in_progress', 'done'], default: 'todo', index: true })
  status: TaskStatus;

  @Prop({ enum: ['low', 'medium', 'high'], default: 'medium' })
  priority: TaskPriority;

  @Prop({ type: Date, default: null })
  dueDate: Date | null;

  @Prop({ type: Date, default: null })
  completedAt: Date | null;

  @Prop({ default: null })
  completedBy: string | null;

  @Prop({ type: [TaskCommentSchema], default: [] })
  comments: TaskComment[];

  /** If this task was generated by the AI agent in a batch, all sibling tasks share this id. */
  @Prop({ default: null, index: true })
  batchId: string | null;

  createdAt: Date;
  updatedAt: Date;
}

export const TaskSchema = SchemaFactory.createForClass(Task);
